spring:
  application:
    name: Idempotency-service
  data:
    redis:
      host: idempotency-data-fte8jb.serverless.aps1.cache.amazonaws.com
      port: 6379
      ssl:
        enabled: true
      timeout: 20s
      connect-timeout: 20s

